export const partnerData = [
  { name: 'GCash', imgSrc: 'icons/gcash.png' },
  { name: 'GrabPay', imgSrc: 'icons/grabpay.png' },
  { name: 'Bayad Center', imgSrc: 'icons/bayad_center.png' },
  { name: 'LBC', imgSrc: 'icons/lbc.jpeg' },
  { name: 'CVM Pawnshop', imgSrc: 'icons/cvm.jpeg' },
  { name: 'Isetann', imgSrc: 'icons/isetann.svg' },
  { name: 'Landmark', imgSrc: 'icons/Landmark.jpg' },
  { name: 'Pera Hub', imgSrc: 'icons/pera_hub.png' },
  { name: 'Raquel Pawnshop', imgSrc: 'icons/raquel.jpeg' },
  { name: "Robinson's Department Store", imgSrc: 'icons/robinson_dep.png' },
  { name: "Robinson's Supermarket", imgSrc: 'icons/robinson_sup.png' },
  { name: "Rustan's Marketplace", imgSrc: 'icons/marketplace.jpg' },
  { name: "Rustan's Supermarket", imgSrc: 'icons/rustans_sup.png' },
  { name: 'Shopwise Express', imgSrc: 'icons/shopwise.jpeg' },
  { name: 'Sinag Pawnshop', imgSrc: 'icons/sinag.jpeg' },
  { name: 'USSC', imgSrc: 'icons/ussc.png' },
  { name: 'Villarica Pawnshop', imgSrc: 'icons/villarica.png' },
];

export const inGameTopup = [
  'Mobile Legends Diamonds',
  'Mobile Legends Twilight Pass',
  'Mobile Legends Starlight Member Plus',
  'Mobile Legends Starlight Member',
  'Mobile Legends Season Pass',
  'Mobile Legends Exclusive Edition Starlight Member',
  'Ragnarok Mobile Zeny',
  'Ragnarok Mobile Premium',
  'Ragnarok Mobile Big Cat Coin',
  'Marvel Super War',
  'One Punch Man',
  'Tom and Jerry: Chase',
  'Sin Tales',
  'Omega Legends',
  'Knights of Valour',
  'Be The King',
  'Dragon Raja Fund',
  'Dragon Raja Coupons',
  'Dragon Brawlers',
  'Idle Legend',
  'Naruto Slug Fest',
  'Devil Hunter',
  'The Elder Scrolls: Legends',
  'Ride Out Heroes Tokens',
  'Ride Out Heroes Privilege',
  'Legacy of Discord-FuriousWings Helper Pack',
  'Legacy of Discord-FuriousWings Diamonds',
  'Era of Celestials Special Ring Fragment Bundle',
  'Era of Celestials Diamond',
  'Era of Celestials Daily Level-up Bundle',
  'Era of Celestial Artifacts Chest',
  'Bleach Kristal',
  'Lords Mobile Diamonds',
  'Audistar Mobile',
  'Lumia Saga Diamonds',
  'Manga Toon Coins',
  'King of Kings VIP',
  'King of Kings Funds',
  'King of Kings Coupons',
  'Eternal City Monthly Card',
  'Eternal City Gem',
  'Saint Seiya Coupons',
  'Laplace M Spirals',
  'Dancing Love',
];

export const vouchers = [
  'Roblox',
  'Steam PHP',
  'Garena Voucher (PH)',
  'PUBG Mobile UC Redeem Code',
  'Nexon Karma Coin US',
  'iTunes Store',
  'UniPin Voucher',
  'Battle.Net',
  'IMVU',
];

export const billers = [
  'Manila Water',
  'Maynilad',
  'SSS Contributions',
  'AsiaPay/PesoPay',
  'RFID',
  'Cignal TV, Inc.',
  'Converge ICT',
  'PLDT/PLDT6',
  'Pag Ibig Fund',
  'NBI',
  'National Housing Authority',
  'Sta. Lucia Realty and Development, Inc.',
  'Bayantel',
  'Unionbank of the Philippines',
  'Smart - Cellular',
  'Cignal Mediascape',
  'Pag-Ibig Fund (HDMF) ',
  'Adamson University',
  'APEC Schools',
  'Lyceum of the Philippines',
  'ICCT Colleges',
  'Sunlife Grepa Financial, Inc.',
  'Manulife',
  'Maxicare Healthcare Corporation',
  'Pru Life Insurance Corporation of U.K.',
  'Sunlife of Canada (Philippines), Inc.',
  'Sunlife Financial Plans, Inc. (Pre-Need)',
  'Philippine Prudential Life Insurance Co. Inc',
  'Bankard, Inc.',
  'Equicom Savings Bank',
  'Bank of Philippine Islands Credit Card',
  'Metrobank Card Corporation',
  'Manila Memorial Park & Cemetery, Inc.',
  'Loyola Plans Consolidated',
  'Avon Cosmetics, Inc. (AVON)',
  'Bankard Inc.',
];
