const modalGames = [
  { name: 'Be The King', src: 'https://cdn.eplayment.com/games/be-the-king.jpg' },
  { name: 'Bleach Kristal', src: 'https://cdn.eplayment.com/games/bleach-kristal.jpg' },
  { name: 'Capsa City', src: 'https://cdn.eplayment.com/games/capsa-city.jpg' },
  { name: 'Crossing Void Global', src: 'https://cdn.eplayment.com/games/crossing-void-global.jpg' },
  { name: 'Devil Hunter', src: 'https://cdn.eplayment.com/games/devil-hunter.jpg' },
  { name: 'Dragon Brawlers', src: 'https://cdn.eplayment.com/games/dragon-brawlers.jpg' },
  { name: 'Dragon Raja', src: 'https://cdn.eplayment.com/games/dragon-raja-coupons.jpg' },
  {
    name: 'Era-of-Celestials',
    src: 'https://cdn.eplayment.com/games/era-of-celestial-artifacts-chest.jpg',
  },
  { name: 'Eternal-City', src: 'https://cdn.eplayment.com/games/eternal-city-gem.jpg' },
  { name: 'Heaven Saga Crystal', src: 'https://cdn.eplayment.com/games/heaven-saga-crystal.jpg' },
  { name: 'Idle Legend', src: 'https://cdn.eplayment.com/games/idle-legend.jpg' },
  { name: 'Knights Of Valour', src: 'https://cdn.eplayment.com/games/knights-of-valour.jpg' },
  { name: 'Laplace M Spirals', src: 'https://cdn.eplayment.com/games/laplace-m-spirals.jpg' },
  {
    name: 'Legacy of Discord Furious Wings',
    src: 'https://cdn.eplayment.com/games/legacy-of-discord-furiouswings-diamonds.jpg',
  },
  { name: 'Life After', src: 'https://cdn.eplayment.com/games/lifeafter.jpg' },
  { name: 'Lords Mobile', src: 'https://cdn.eplayment.com/games/lords-mobile-diamonds.jpg' },
  { name: 'Lumia Saga', src: 'https://cdn.eplayment.com/games/lumia-saga-diamonds.jpg' },
  { name: 'Manga Toon', src: 'https://cdn.eplayment.com/games/manga-toon-coins.jpg' },
  { name: 'Marvel Super War', src: 'https://cdn.eplayment.com/games/marvel-super-war.jpg' },
  { name: 'Mobile Legends', src: 'https://cdn.eplayment.com/games/mobile-legends-diamonds.jpg' },
  { name: 'MU Origin', src: 'https://cdn.eplayment.com/games/mu-origin-2.jpg' },
  { name: 'Naruto Slugfest', src: 'https://cdn.eplayment.com/games/naruto-slugfest-x-gold.jpg' },
  { name: 'Omega Legends', src: 'https://cdn.eplayment.com/games/omega-legends.jpg' },
  { name: 'One Punch Man', src: 'https://cdn.eplayment.com/games/one-punch-man.jpg' },
  { name: 'Point Blank PH', src: 'https://cdn.eplayment.com/games/point-blank-ph.jpg' },
  {
    name: 'Ragnarok Mobile',
    src: 'https://cdn.eplayment.com/games/ragnarok-mobile-big-cat-coin.jpg',
  },
  { name: 'Ride Out Heroes', src: 'https://cdn.eplayment.com/games/ride-out-heroes-privilege.jpg' },
  {
    name: 'The Elder Scrolls Legends',
    src: 'https://cdn.eplayment.com/games/the-elder-scrolls-legends.jpg',
  },
  { name: 'Tom And Jerry Chase', src: 'https://cdn.eplayment.com/games/tom-and-jerry-chase.jpg' },
];

export default modalGames;
